<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.Job</code>
 */
class Job extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string company_name = 3;</code>
     */
    protected $company_name = '';
    /**
     * Generated from protobuf field <code>.protobuf.SalaryRange salary_range = 4;</code>
     */
    protected $salary_range = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $name
     *     @type string $company_name
     *     @type \Protobuf\SalaryRange $salary_range
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_name = 3;</code>
     * @return string
     */
    public function getCompanyName()
    {
        return $this->company_name;
    }

    /**
     * Generated from protobuf field <code>string company_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protobuf.SalaryRange salary_range = 4;</code>
     * @return \Protobuf\SalaryRange
     */
    public function getSalaryRange()
    {
        return $this->salary_range;
    }

    /**
     * Generated from protobuf field <code>.protobuf.SalaryRange salary_range = 4;</code>
     * @param \Protobuf\SalaryRange $var
     * @return $this
     */
    public function setSalaryRange($var)
    {
        GPBUtil::checkMessage($var, \Protobuf\SalaryRange::class);
        $this->salary_range = $var;

        return $this;
    }

}

