<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.JobCardRp</code>
 */
class JobCardRp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string city_name = 3;</code>
     */
    protected $city_name = '';
    /**
     * Generated from protobuf field <code>int64 quantity = 4;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>string experience_name = 5;</code>
     */
    protected $experience_name = '';
    /**
     * Generated from protobuf field <code>string education_name = 6;</code>
     */
    protected $education_name = '';
    /**
     * Generated from protobuf field <code>string category_name = 7;</code>
     */
    protected $category_name = '';
    /**
     * Generated from protobuf field <code>string company_name = 8;</code>
     */
    protected $company_name = '';
    /**
     * Generated from protobuf field <code>string status = 9;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>int64 num_views = 11;</code>
     */
    protected $num_views = 0;
    /**
     * Generated from protobuf field <code>int64 num_posts = 12;</code>
     */
    protected $num_posts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $city_name
     *     @type int|string $quantity
     *     @type string $experience_name
     *     @type string $education_name
     *     @type string $category_name
     *     @type string $company_name
     *     @type string $status
     *     @type string $updated_at
     *     @type int|string $num_views
     *     @type int|string $num_posts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city_name = 3;</code>
     * @return string
     */
    public function getCityName()
    {
        return $this->city_name;
    }

    /**
     * Generated from protobuf field <code>string city_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCityName($var)
    {
        GPBUtil::checkString($var, True);
        $this->city_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 quantity = 4;</code>
     * @return int|string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int64 quantity = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string experience_name = 5;</code>
     * @return string
     */
    public function getExperienceName()
    {
        return $this->experience_name;
    }

    /**
     * Generated from protobuf field <code>string experience_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setExperienceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->experience_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string education_name = 6;</code>
     * @return string
     */
    public function getEducationName()
    {
        return $this->education_name;
    }

    /**
     * Generated from protobuf field <code>string education_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEducationName($var)
    {
        GPBUtil::checkString($var, True);
        $this->education_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_name = 7;</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->category_name;
    }

    /**
     * Generated from protobuf field <code>string category_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_name = 8;</code>
     * @return string
     */
    public function getCompanyName()
    {
        return $this->company_name;
    }

    /**
     * Generated from protobuf field <code>string company_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 9;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num_views = 11;</code>
     * @return int|string
     */
    public function getNumViews()
    {
        return $this->num_views;
    }

    /**
     * Generated from protobuf field <code>int64 num_views = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumViews($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_views = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num_posts = 12;</code>
     * @return int|string
     */
    public function getNumPosts()
    {
        return $this->num_posts;
    }

    /**
     * Generated from protobuf field <code>int64 num_posts = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumPosts($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_posts = $var;

        return $this;
    }

}

