<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto

namespace Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.SalaryRange</code>
 */
class SalaryRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 min = 1;</code>
     */
    protected $min = 0;
    /**
     * Generated from protobuf field <code>int32 max = 2;</code>
     */
    protected $max = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $min
     *     @type int $max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Job::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 min = 1;</code>
     * @return int
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Generated from protobuf field <code>int32 min = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkInt32($var);
        $this->min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max = 2;</code>
     * @return int
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>int32 max = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkInt32($var);
        $this->max = $var;

        return $this;
    }

}

